
services:
  pg_tileserv:
    image: jamrow/maps:latest
    container_name: maps
    restart: always
    secrets:
      - DATABASE_URL
    ports:
      - "7800:7800"
    deploy:
      replicas: 1
      restart_policy:
        condition: none

secrets:
  DATABASE_URL:
    external: true