
services:
  pg_tileserv:
    image: jamrow/maps:${IMAGE_TAG}
    container_name: maps
    restart: always
    secrets:
      - DATABASE_URL
    ports:
      - "7800:7800"
    environment:
      DATABASE_URL: "postgresql://postgres.mgvaztrwyspjhzqohbqt:Fws0K2Pb0AR6blw2@aws-0-us-west-1.pooler.supabase.com:5432/postgres"

secrets:
  DATABASE_URL:
    external: true