
services:
  pg_tileserv:
    image: jamrow/maps:latest
    restart: always
    env_file:
      - /root/.env
    networks:
      - frontend
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.maps-http.rule=Host(`maps.api.shmaxes.com`) && PathPrefix(`/`)"
        - "traefik.http.routers.maps-http.entrypoints=web"
        - "traefik.http.services.maps-http.loadbalancer.server.port=7800"
      replicas: 1
      restart_policy:
        condition: on-failure
  traefik:
    image: traefik:v3.4
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
    restart: unless-stopped
    networks:
      - frontend


networks:
  frontend:
    external: true