
services:
  pg_tileserv:
    image: jamrow/maps:latest
    restart: always
    env_file:
      - /root/env.env
    ports:
      - "7800:7800"
    deploy:
      replicas: 1
      restart_policy:
        condition: none

secrets:
  DATABASE_URL:
    external: true