
services:
  pg_tileserv:
    image: jamrow/maps:latest
    restart: always
    env_file:
      - /root/.env
    networks:
      - frontend
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.maps-https.loadbalancer.server.port=7800"
        - "traefik.http.routers.maps-https.tls=true"
        - "traefik.http.routers.maps-https.tls.certresolver=cloudflare"
        - "traefik.http.routers.maps-https.entrypoints=websecure"
        - "traefik.http.routers.maps-https.rule=Host(`maps.shmaxes.com`)"
      replicas: 1
      restart_policy:
        condition: on-failure
  traefik:
    image: traefik:v3.4
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./data/certs:/var/traefik/certs:rw
    restart: unless-stopped
    networks:
      - frontend
    env_file:
      - /root/.env


networks:
  frontend:
    external: true