
services:
  pg_tileserv:
    image: jamrow/maps:${IMAGE_TAG}
    container_name: maps
    restart: always
    secrets:
      - DATABASE_URL
    ports:
      - "7800:7800"
    environment:
      DATABASE_URL: "/run/secrets/DATABASE_URL"

secrets:
  DATABASE_URL:
    external: true